from models.solver import solve
from results.mean_var import average_excel_solutions
import numpy as np
import pandas as pd
import math
import time

#########################################################################
#################   SOLVER ATO PRICING - MULTI-STAGE    #################
#########################################################################

### PARAMETERS ###

##############################################
# GENERAL SIZE #
comp = 3
prod = 2
stages = 9
branching = [2] * (stages - 1) # Binary tree
scenarios = math.prod(branching)
##############################################


##############################################
# BILL OF MATERIALS 
# Here we have 2 options: 
#   define randomly the BoM, where products use an amount of components between [min_use, max_use]
#   or use a specific BoM defined in parameters.py (W model, N model, etc)
min_use = 2
max_use = 3
w_model = False
##############################################


##############################################
# PRICES
# The discrete set of prices defined by [lb_price, ub_price] in steps of step_price.
# i.e, the discrete set [30,50] in steps of 2: [30, 32, 34,..., 48, 50]
lb_price = 50
ub_price = 100
step_price = 5
##############################################


##############################################
# COSTS
# Similar to how the discrete set of prices work. Define the set [min_cost, max_cost] in steps of five 
# (the steps can be modified in params.py)
min_cost = 5
max_cost = 25
inv_factor = 0.15
# I0: quantity to satisfy expected demand at given price
# select price --> determine expected demand --> satisfy initial inventory 
I0 = np.max([lb_price, ub_price]) 
##############################################


##############################################
# MULTIPLICATIVE STOCHASTIC COMPONENT - DEMAND
# epsilon: given by a uniform distribution U[lb_epsilon, ub_epsilon]
lb_epsilon = 0.5
ub_epsilon = 1.5
##############################################
# ADDITIVE STOCHASTIC COMPONENT - DEMAND
# delta: given by a normal distribution N(mu_delta, std_delta)
mu_delta = 0
std_delta = 8
##############################################
# PRICE LINEAR EXPRESSION - DEMAND
# Decreasing linnear expression for the demand. given by: (a - b * w)
a = 200
b = 2.0
##############################################


##############################################
# LEAD TIMES
# lead times are randomly generated by a uniform dist U[lb_L,ub_L]. 
# in our work we can simply change between deterministic or stochastic lead times. 
#   For deterministic: L = L[i,t]
#   For stochastic: L = L[i,t,s]
lb_L = 1
ub_L = 2
det = False # False for stochastic lead times (While we tested with deterministic, we mostly focus in stochastic)
##############################################


##############################################
# UNCERTAINTY ANALYSIS 
# We can calculate the following metrics for uncertainty analysis:
#   - VSS: Value of the Stochastic Solution
#   - EVPI: Expected Value of Perfect Information
#   - VSS_TS: Value of Stochastic Solution based on two stage model
vss_calc = False
evpi_calc = False
vss_ts_calc = False   
##############################################


##############################################
# EXPERIMENTAL SETTINGS
show_var = False   # export solution in an excel file. Can be used to fine analisys of decision behavior.
#=============================================
lambda_app = True   # Save lambda for affine function approximation. if solving standard multistage, it will fix a pricing policy.
lambda_benders = False   # lala
#=============================================
show_heatmap = False   # Save heatmaps to figures for every decision variable
show_boxplot = False   # Save boxplot to figures for every decision variable
show_candlestick = True   # Save candlestick to figures for every decision variable
#=============================================
time_limit = 500
seed = 5
n_instances = 11
##############################################


#=============================================
# SPECIFIC CONFIGS (one at a time)
# in this research we explore the ATO problem with several model formulations. They are detailed below.
# depending on their nature, thwy will be in either the models or the sol_approach folders.

Model = "MS_linear"

#   "MS" -> Standard multistage model.
#   "MS_FP" -> multistage with pricing as first stage decision.

#   "MS_linear" -> multistage with linealized revenue (MILP). 

#   "MS_linear_affine" -> multistage with linealized revenue AND affine pricing policy.
#   "Benders" -> Benders with affine function approximation.
#=============================================


size = comp, prod, stages, scenarios, branching, seed, time_limit
bom = min_use, max_use, w_model
costs = min_cost, max_cost, inv_factor, I0
price_param = lb_price, ub_price, step_price
demand = a, b, lb_epsilon, ub_epsilon, mu_delta, std_delta
lead_times = lb_L, ub_L, det 
show = show_var, lambda_app, lambda_benders, show_heatmap, show_boxplot, show_candlestick, vss_calc, evpi_calc, vss_ts_calc, Model

#solve(size, bom, costs, price_param, demand, lead_times, show)

seeds = [seed + i for i in range(n_instances)]
results = []
files = []

for seed in seeds:
    size = comp, prod, time, scenarios, branching, seed, time_limit
    res = solve(size, bom, costs, price_param, demand, lead_times, show)
    results.append(res)
    files.append(f"var_data/MS_DL_inst{seed}.xlsx" if det else f"var_data/MS_SL_inst{seed}.xlsx")
    

df = pd.DataFrame(results)
df.to_csv(f"var_data/metrics_inst.csv", index=True)

average_excel_solutions(files, output_path="var_data/mean_vars_by_inst/avg_sol.xlsx")